### ISSUE TITLE
Doesn't out of order responses break HTTP?

### ISSUE THREAD

**Issue by kellabyte** [valyala/httpteleport#2]
Why does the README talk about supporting out of order responses and avoiding the head-of-line problem? Won't that break existing HTTP clients? I'm probably just misunderstanding :)

**Comment by valyala** [comment]
`httpteleport` client and server use custom protocol which is incompatible with HTTP, so existing HTTP clients cannot talk to `httpteleport` servers.

The `httpteleport` client generates an unique id for each request and prepends the request by this id before sending to the remote server. The remote server prepends each response with the request id, so the client could properly associate received responses with sent requests.

**Comment by valyala** [comment]
HTTP client usually talks to HTTP proxy:

`HTTP client` <- HTTP protocol -> `HTTP proxy, that uses httpteleport client for proxying reuqests to the server` <- httpteleport protocol -> `httpteleport server`
